### ISSUE TITLE
Routing : add queryStrings support to PageManager#navigateToRoute

### ISSUE THREAD

**Issue by sesegura** [hulilabs/ju-mvc#11]
Currently there's no support on `PageManager` or `Router` for adding query strings to the URL. 

The usual way for handling URL params is to set optional params on the route definition, but this may be inconvenient in certain cases where the correct approach (or at least, one of the best approaches) is to use query strings.

For example: when a search or a filter with single or multiple criteria must be performed and the result of these operations could be a empty set, query strings could be used, instead of returning a 404 status if the route doesn't match the route params given.

`(...)/examples/invalidparam` could return 404 because the route may not match a defined route
`(...)/examples?param=invalid` could return a 200 status but with an empty set as response and the application may be able to handle this case.

**Comment by jpgarbanzo** [comment]
@sesegura thanks!
